web/apps/article/urls.py
from django.urls import path

from . import feed
from .views import ArticleDetailView, ArticleCategoryView, ArticleStarView, LabelArticleView, MySearchView, TimeLineView

app_name = 'article'

urlpatterns = [
    path("detail/<int:article_id>/", ArticleDetailView.as_view(), name='detail'),
    path("category/<int:category_id>/", ArticleCategoryView.as_view(), name='category_article'),
    path("star/<int:article_id>/", ArticleStarView.as_view(), name='article_star'),
    path("label/<int:label_id>/", LabelArticleView.as_view(), name='label_article'),
    # path('categories/', GetCategories.as_view()),
    path('search', MySearchView(), name='search'),
    path('time', TimeLineView.as_view(), name='time'),
    path('rss/', feed.BlogFeed(), name='rss'),

]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import xadmin
from web import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path("article/", include('article.urls')),
    path('mdeditor/', include('mdeditor.urls')),
    path('link/', include('link.urls')),
    path('user/', include('user.urls')),
    path('xadmin/', xadmin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = views.page_not_found
handler500 = views.server_error

web/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}">
    {% block title %}
    {% endblock %}
    <link rel='stylesheet' id='caozhuti-style-css' href="{% static 'css/style-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='external-css' href="{% static 'css/external-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='sweetalert2-css' href="{% static 'css/sweetalert2.min-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='app-css' href="{% static 'css/app-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='diy-css' href="{% static 'css/diy-4.9.css' %}" type='text/css' media='all'>
    <script type='text/javascript' src="{% static 'js/jquery-2.2.4.min-2.2.4.js' %}"></script>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}" media="all">
    <script type='text/javascript' src="{% static 'layui/layui.js'%}"></script>
    <meta name="keywords" content="Fred，Fred的个人网站，个人博客，Fred的个人博客">
    {% block script %}
    {% endblock %}
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. --><!--[if lt IE 9]>
    <script src="static/js/html5shiv.js"></script>
    <script src="static/js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="archive category category-adver category-61 hfeed navbar-sticky_transparent navbar-slide sidebar-none pagination-infinite_button">
<div class="site">
    <header class="site-header">
        <div class="container">
            <div class="navbar">
                <div class="logo-wrapper">
                    <a href="/">
                        <img class="logo regular tap-logo" src="{% static 'picture/logo.png' %}" data-dark="" alt="Fred">
                    </a>
                </div>
                <div class="sep">
                </div>
                <nav class="main-menu hidden-xs hidden-sm hidden-md">
                    <ul id="menu-menu-1" class="nav-list u-plain-list">
                        <li id="menu-item-34" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item menu-item-home menu-item-34"><a href="/">首页</a></li>
                        {% for category in categories %}
                            <li id="menu-item-85" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-85"><a href="{% url 'article:category_article' category.category.id %}">{{category.category.name}}</a>
                            {% if category.sub_categories %}
                                <ul class="sub-menu">
                                    {% for sub_category in category.sub_categories%}
                                        <li id="menu-item-86" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-86"><a href="{% url 'article:category_article' sub_category.id %}">{{sub_category}}</a></li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                            </li>
                        {% endfor %}
                        <li id="menu-item-34" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item menu-item-home menu-item-34"><a href="{% url 'article:time' %}">文章归档</a></li>
                        <li id="menu-item-34" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item menu-item-home menu-item-34"><a href="{% url 'article:rss' %}">RSS</a></li>
                    </ul>
                </nav>
                <div class="main-search">
                    <form method="get" class="search-form inline" action="{% url 'article:search' %}">
                        <input type="search" class="search-field inline-field" placeholder="输入关键词，回车..." autocomplete="off" value="" name="q" required="required">
                        <button type="submit" class="search-submit"><i class="mdi mdi-magnify"></i></button>
                    </form>
                    <div class="search-close navbar-button">
                        <i class="mdi mdi-close"></i>
                    </div>
                </div>
                <div class="actions">
                    <div class="search-open navbar-button">
                        <i class="mdi mdi-magnify"></i>
                    </div>
                    <div class="burger">
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="header-gap">
    </div>
{% block content %}
{% endblock %}
    <!-- end sitecoent -->
    <div class="module parallax">
        <img class="jarallax-img lazyload" data-srcset="{% static 'picture/timg.jpg' %}" data-sizes="auto" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="">
        <div class="container">
            <h4 class="entry-title">
                提供最优质的资源集合
            </h4>
            <a class="button" href="/">立即查看</a>
            <a class="button transparent" href="mailto:ltfred@163.com">联系作者</a>
        </div>
    </div>
    <footer class="site-footer">
        <div class="container">
            <div class="footer-widget">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-3 widget--about">
                        <div class="widget--content">
                            <div class="footer--logo mb-20">
                                <img class="tap-logo" src="{% static 'picture/logo2.png' %}" data-dark="" alt="Fred" width="100px" height="50px">
                            </div>
                            <p class="mb-10">
                                Fred一个90后小青年，热爱生活和旅游，喜欢冒险。爱自己，你要活得无可替代并精彩绝伦，世界那么大不如去看看它，人活着不只有眼前的苟且，还有诗和远方，以爱与青春为名，陪你一路成长，不失初心，不忘初衷!
                            </p>
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
                    <div class="col-xs-12 col-sm-3 col-md-2 col-md-offset-1 widget--links">
                        <div class="widget--title">
                            <h5>本站导航</h5>
                        </div>
                        <div class="widget--content">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#">关于我们</a></li>
                                <li><a href="#">充值说明</a></li>
                                <li><a href="#">下载说明</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
                    <div class="col-xs-12 col-sm-3 col-md-2 widget--links">
                        <div class="widget--title">
                            <h5>更多介绍</h5>
                        </div>
                        <div class="widget--content">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#">隐私协议</a></li>
                                <li><a href="#">权限说明</a></li>
                                <li><a href="#">账户中心</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
                    <div class="col-xs-12 col-sm-3 col-md-2 widget--links">
                        <div class="widget--title">
                            <h5 style='text-align:center'>微信号</h5>
                        </div>
                        <div class="widget--content">
                            <img src="{% static 'image/weixin.jpeg' %}">
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
{#                    <div class="col-xs-12 col-sm-3 col-md-2 widget--links">#}
{#                        <div class="widget--title">#}
{#                            <h5 style='text-align:center'>博客小程序</h5>#}
{#                        </div>#}
{#                        <div class="widget--content">#}
{#                            <img src="/static/picture/44c6c370fd18593.jpg">#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
            <div class="site-info">
                © Fred   ww.aliwen.vip
            </div>
        </div>
    </footer>
    <div class="rollbar">
        <div class="rollbar-item" etap="to_top">
            <i class="fa fa-angle-up"></i>
        </div>
    </div>
    <div class="dimmer">
    </div>
    <div class="off-canvas">
        <div class="canvas-close">
            <i class="mdi mdi-close"></i>
        </div>
        <div class="logo-wrapper">
            <a href="index.html">
                <img class="logo regular" src="{% static 'picture/logo.png' %}" alt="Fred">
            </a>
        </div>
        <div class="mobile-menu hidden-lg hidden-xl">
        </div>
        <aside class="widget-area">
        </aside>
    </div>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.css">
    <script src="https://cdn.jsdelivr.net/npm/aplayer@1.10.1/dist/APlayer.min.js"></script>
    <div id="aplayer" class="aplayer"  data-id="3347806" data-server="netease" data-type="playlist" data-fixed="true" data-listfolded="true" data-order="list" data-theme="#F58EA8" style="width: 100%"></div>
    <script src="https://unpkg.com/meting@1.2/dist/Meting.min.js"></script>
    <script type='text/javascript' src="{% static 'js/sweetalert2.min-4.9.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/plugins-4.9.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/app-4.9.js' %}"></script>
    <link rel="stylesheet" type="text/css" rel="external nofollow" target="_blank" href="{% static 'css/sweetalert.min.css' %}">
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/mouse.js' %}"></script>
    <script src="https://eqcn.ajz.miesnfu.com/wp-content/plugins/wp-3d-pony/live2dw/lib/L2Dwidget.min.js"></script>
    <script>
        L2Dwidget.init({
            "model": {
                jsonPath: "https://unpkg.com/live2d-widget-model-miku@1.0.5/assets/miku.model.json",
                "scale": 1
            },
            "display": {
                "position": "right",
                "width": 80,
                "height": 160,
                "hOffset": 0,
                "vOffset": -20
            },
            "mobile": {
                "show": true,
                "scale": 0.5
            },
            "react": {
                "opacityDefault": 0.3,
                "opacityOnHover": 0.2
            }
        });
    </script>
{% block pagejs %}
{% endblock %}
</div>
</body>
</html>

web/templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}">
    {% block title %}
    {% endblock %}
    <link rel='stylesheet' id='caozhuti-style-css' href="{% static 'css/style-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='external-css' href="{% static 'css/external-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='sweetalert2-css' href="{% static 'css/sweetalert2.min-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='app-css' href="{% static 'css/app-4.9.css' %}" type='text/css' media='all'>
    <link rel='stylesheet' id='diy-css' href="{% static 'css/diy-4.9.css' %}" type='text/css' media='all'>
    <script type='text/javascript' src="{% static 'js/jquery-2.2.4.min-2.2.4.js' %}"></script>
    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}" media="all">
    <script type='text/javascript' src="{% static 'layui/layui.js'%}"></script>
    {% block script %}
    {% endblock %}
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. --><!--[if lt IE 9]>
    <script src="static/js/html5shiv.js"></script>
    <script src="static/js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="archive category category-adver category-61 hfeed navbar-sticky_transparent navbar-slide sidebar-none pagination-infinite_button">
<div class="site">
    <header class="site-header">
        <div class="container">
            <div class="navbar">
                <div class="logo-wrapper">
                    <a href="index.html">
                        <img class="logo regular tap-logo" src="{% static 'picture/logo.png' %}" data-dark="" alt="Fred">
                    </a>
                </div>
                <div class="sep">
                </div>
                <nav class="main-menu hidden-xs hidden-sm hidden-md">
                    <ul id="menu-menu-1" class="nav-list u-plain-list">
                        <li id="menu-item-34" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item menu-item-home menu-item-34"><a href="/">首页</a></li>
                        {% for category in categories %}
                            <li id="menu-item-85" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-85"><a href="{% url 'article:category_article' category.category.id %}">{{category.category.name}}</a>
                                <ul class="sub-menu">
                                    {% for sub_category in category.sub_categories%}
                                        <li id="menu-item-86" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-86"><a href="{% url 'article:category_article' sub_category.id %}">{{sub_category}}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                </nav>
                <div class="main-search">
                    <form method="get" class="search-form inline" action="{% url 'article:search' %}">
                        <input type="search" class="search-field inline-field" placeholder="输入关键词，回车..." autocomplete="off" value="" name="q" required="required">
                        <button type="submit" class="search-submit"><i class="mdi mdi-magnify"></i></button>
                    </form>
                    <div class="search-close navbar-button">
                        <i class="mdi mdi-close"></i>
                    </div>
                </div>
                <div class="actions">
                    <div class="search-open navbar-button">
                        <i class="mdi mdi-magnify"></i>
                    </div>
                    <div class="burger">
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="header-gap">
    </div>
{% block content %}
{% endblock %}
    <!-- end sitecoent -->
    <div class="module parallax">
        <img class="jarallax-img lazyload" data-srcset="{% static 'picture/timg.jpg' %}" data-sizes="auto" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" alt="">
        <div class="container">
            <h4 class="entry-title">
                提供最优质的资源集合
            </h4>
            <a class="button" href="index1.html">立即查看</a>
            <a class="button transparent" href="javascript:;">联系作者</a>
        </div>
    </div>
    <footer class="site-footer">
        <div class="container">
            <div class="footer-widget">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-3 widget--about">
                        <div class="widget--content">
                            <div class="footer--logo mb-20">
                                <img class="tap-logo" src="{% static 'picture/logo.png' %}" data-dark="" alt="Fred">
                            </div>
                            <p class="mb-10">
                                Aliwen一个90后小青年，热爱生活和旅游，喜欢冒险。爱自己，你要活得无可替代并精彩绝伦，世界那么大不如去看看它，人活着不只有眼前的苟且，还有诗和远方，以爱与青春为名，陪你一路成长，不失初心，不忘初衷!
                            </p>
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
                    <div class="col-xs-12 col-sm-3 col-md-2 col-md-offset-1 widget--links">
                        <div class="widget--title">
                            <h5>本站导航</h5>
                        </div>
                        <div class="widget--content">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#">关于我们</a></li>
                                <li><a href="#">充值说明</a></li>
                                <li><a href="#">下载说明</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
                    <div class="col-xs-12 col-sm-3 col-md-2 widget--links">
                        <div class="widget--title">
                            <h5>更多介绍</h5>
                        </div>
                        <div class="widget--content">
                            <ul class="list-unstyled mb-0">
                                <li><a href="#">隐私协议</a></li>
                                <li><a href="#">权限说明</a></li>
                                <li><a href="#">账户中心</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
                    <div class="col-xs-12 col-sm-3 col-md-2 widget--links">
                        <div class="widget--title">
                            <h5 style='text-align:center'>微信公众号</h5>
                        </div>
                        <div class="widget--content">
                            <img src="/static/picture/ca3af5e69a6da7d.jpg">
                        </div>
                    </div>
                    <!-- .col-md-2 end -->
                    <div class="col-xs-12 col-sm-3 col-md-2 widget--links">
                        <div class="widget--title">
                            <h5 style='text-align:center'>博客小程序</h5>
                        </div>
                        <div class="widget--content">
                            <img src="/static/picture/44c6c370fd18593.jpg">
                        </div>
                    </div>
                </div>
            </div>
            <div class="site-info">
                © Fred   ww.aliwen.vip
            </div>
        </div>
    </footer>
    <div class="rollbar">
        <div class="rollbar-item" etap="to_top">
            <i class="fa fa-angle-up"></i>
        </div>
    </div>
    <div class="dimmer">
    </div>
    <div class="off-canvas">
        <div class="canvas-close">
            <i class="mdi mdi-close"></i>
        </div>
        <div class="logo-wrapper">
            <a href="index.html">
                <img class="logo regular" src="{% static 'picture/logo.png' %}" alt="Fred">
            </a>
        </div>
        <div class="mobile-menu hidden-lg hidden-xl">
        </div>
        <aside class="widget-area">
        </aside>
    </div>
    <script type='text/javascript' src="{% static 'js/sweetalert2.min-4.9.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/plugins-4.9.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/app-4.9.js' %}"></script>
    <link rel="stylesheet" type="text/css" rel="external nofollow" target="_blank" href="{% static 'css/sweetalert.min.css' %}">
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/mouse.js' %}"></script>
{% block pagejs %}
{% endblock %}
</div>
</body>
</html>

web/templates/label_article.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Fred-{{label.name}}-Fred</title>
{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
    <div class="term-bar lazyload visible" data-bg="{% static 'picture/123.jpg' %}">
        <h1 class="term-title">标签：{{label.name}}</h1>
    </div>
    <div class="site-content">
        <div class="container">
            <div class="filter&#45;&#45;content">
                <form class="mb-0" method="get" action="#">
                    <input type="hidden" name="s">
                    <div class="form-box search-properties mb-0">
                        <div class="filter-item">
                            <ul class="filter-tag">
                                <span><i class="fa fa-folder-open-o"></i> 标签：</span>
                                {% for label in labels_and_count %}
                                    <li><a href="{% url 'article:label_article' label.label.id %}">{{label.label.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="content-area">
                        <main class="site-main">
                            <div class="row posts-wrapper">
                                {% for article in label_articles %}
                                    <div class="col-sm-6 col-md-4 col-lg-3">
                                        <article id="post-118" class="post post-grid post-118 type-post status-publish format-standard has-post-thumbnail hentry category-ui category-adver category-design tag-ui tag-81">
                                            <div class="entry-media">
                                                <div class="placeholder" style="padding-bottom: 66.666666666667%;">
                                                    <a href='{% url 'article:detail' article.id %}'><img src="{{article.cover}}" alt=""></a>
                                                </div>
                                            </div>
                                            <div class="entry-wrapper">
                                                <header class="entry-header">
                                                    <div class="entry-meta">
									            <span class="meta-author">
									                <a href="#"><img alt='' data-src='{{article.author.avatar}}' class='lazyload avatar avatar-40 photo ' height='40' width='40'>{{article.author.nickname}}</a>
									            </span>
                                                        <span class="meta-category">
                                                    {% for label in article.labels.all %}
                                                        <a href="/article/label/{{label.id}}" rel="category"><i class="dot"></i>{{ label.name }}</a>
                                                    {% endfor %}
												</span>
                                                    </div>
                                                    <h2 class="entry-title"><a href="/article/detail/{{article.id}}" rel="bookmark">{{article.title}}</a></h2>
                                                </header>
                                                <div class="entry-excerpt u-text-format">
                                                    {{article.des}}
                                                </div>
                                                <div class="entry-footer">
                                                    <a href="javascript:;"><time datetime="2019-07-25T13:51:09+08:00"><i class="fa fa-clock-o"></i> {{article.create_time| date:'Y年m月d日' }}</time></a>
                                                    <a href="javascript:;"><span><i class="fa fa-eye"></i> {{article.view_count}}</span></a>
                                                    <a href="javascript:;"><span><i class="fa fa-star-o"></i>{{article.comment_count}}</span></a>
                                                </div>
                                            </div>
                                        </article>
                                    </div>
                                {% endfor %}
                            </div>
                            <!--                            分页-->
                            {% if label_articles %}
                                <div id="test1" style="margin:0 auto;text-align: center"></div>
                            {% endif %}
                            {% if not label_articles %}
                                <div class="col-12 _404">
                                    <div class="_404-inner">
                                        <h1 class="entry-title">暂无内容</h1>
                                        <div class="entry-content">抱歉，没有找到您需要的文章，可以搜索看看</div>
                                        <form method="get" class="search-form inline" action="{% url 'article:search' %}">
                                            <input type="search" class="search-field inline-field" placeholder="输入关键词，回车..." autocomplete="off" value="" name="q" required="required">
                                            <button type="submit" class="search-submit"><i class="mdi mdi-magnify"></i></button>
                                        </form>
                                    </div>
                                </div>
                            {% endif %}
                        </main>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block pagejs %}
    <script>
        layui.use('laypage', function(){
            var laypage = layui.laypage;

            laypage.render({
                elem: 'test1'
                ,limit:12
                ,theme:'#34495e'
                ,count: {{total_page}} //数据总数，从服务端得到
                ,jump: function(obj, first){
                    //obj包含了当前分页的所有参数，比如：
                    console.log(obj.curr); //得到当前页，以便向服务端请求对应页的数据。
                    console.log(obj.limit); //得到每页显示的条数
                    //首次不执行
                    if(!first){
                        //do something
                        current_page = obj.curr
                        location.href = '/article/label/{{label.id}}?page=' + current_page
                    }
                }
            });
        });
    </script>
{% endblock %}

web/templates/time_line.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Fred-文章归档</title>
{% endblock %}

{% block script %}
{% endblock %}

{% block content %}
    <div class="term-bar lazyload visible" data-bg="{% static 'picture/123.jpg' %}">
        <h1 class="term-title">文章归档</h1>
    </div>
    <div class="site-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="content-area">
                        <main class="site-main">
                            <div class="row posts-wrapper">
                                    <ul class="layui-timeline">
                                        {% for article in articles %}
                                        <a href="{% url 'article:detail' article.id %}">
                                        <li class="layui-timeline-item">
                                            <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                                            <div class="layui-timeline-content layui-text">
                                                <h3 class="layui-timeline-title">{{article.create_time| date:'Y年m月d日' }}</h3>
                                                <p>
                                                <h4>{{ article.title }}</h4>
                                                </p>
                                            </div>
                                        </li>
                                        </a>
                                        {% endfor %}
                                    </ul>
                            </div>
                            <!--                            分页-->
                            {% if articles %}
                                <div id="test1" style="margin:0 auto;text-align: center"></div>
                            {% endif %}
                            {% if not articles %}
                                <div class="col-12 _404">
                                    <div class="_404-inner">
                                        <h1 class="entry-title">暂无内容</h1>
                                        <div class="entry-content">抱歉，没有找到您需要的文章，可以搜索看看</div>
                                        <form method="get" class="search-form inline" action="{% url 'article:search' %}">
                                            <input type="search" class="search-field inline-field" placeholder="输入关键词，回车..." autocomplete="off" value="" name="q" required="required">
                                            <button type="submit" class="search-submit"><i class="mdi mdi-magnify"></i></button>
                                        </form>
                                    </div>
                                </div>
                            {% endif %}
                        </main>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block pagejs %}
    <script>
        layui.use('laypage', function(){
            var laypage = layui.laypage;

            laypage.render({
                elem: 'test1'
                ,limit:12
                ,theme:'#34495e'
                ,count: {{ count }} //数据总数，从服务端得到
                ,jump: function(obj, first){
                    //obj包含了当前分页的所有参数，比如：
                    console.log(obj.curr); //得到当前页，以便向服务端请求对应页的数据。
                    console.log(obj.limit); //得到每页显示的条数
                    //首次不执行
                    if(!first){
                        //do something
                        current_page = obj.curr
                        location.href = '/article/time?page=' + current_page
                    }
                }
            });
        });
    </script>
{% endblock %}